# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_calibration_date', models.DateField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_tnumber', models.CharField(max_length=256)),
                ('eq_brand', models.CharField(max_length=256)),
                ('eq_model', models.CharField(max_length=256)),
                ('eq_purchased_date', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_warranty_start_date', models.CharField(max_length=256)),
                ('eq_warranty_end_date', models.CharField(max_length=256)),
                ('eq_tnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Equipment')),
            ],
        ),
        migrations.AddField(
            model_name='calibration',
            name='eq_tnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Equipment'),
        ),
    ]
