# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibration',
            old_name='eq_calibration_date',
            new_name='calibration_date',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='eq_tnumber',
            new_name='tnumber',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='eq_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='eq_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='eq_purchased_date',
            new_name='purchased_date',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='eq_tnumber',
            new_name='tnumber',
        ),
        migrations.RenameField(
            model_name='warranty',
            old_name='eq_tnumber',
            new_name='tnumber',
        ),
        migrations.RenameField(
            model_name='warranty',
            old_name='eq_warranty_end_date',
            new_name='warranty_end_date',
        ),
        migrations.RenameField(
            model_name='warranty',
            old_name='eq_warranty_start_date',
            new_name='warranty_start_date',
        ),
    ]
