# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20171227_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(default='s', max_length=256),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.CharField(default='s', max_length=256),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manual',
            field=models.CharField(default='s', max_length=256),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(default='s', max_length=256),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchased_date',
            field=models.DateField(max_length=256),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tnumber',
            field=models.CharField(max_length=20),
        ),
    ]
